rpc:
  blocks:
    blocksPerRequest: 1000
    batchDelay: 0
  logs:
    blocksPerRequest: 400
    batchDelay: 100
  traces:
    enabled: true
    blocksPerRequest: 200
    batchDelay: 100

log:
  level: debug
  pretty: true

poller:
  enabled: true
  interval: 3000
  blocksPerPoll: 10000

committer:
  enabled: true
  interval: 1000
  blocksPerCommit: 10000

failureRecoverer:
  enabled: true
  interval: 10000
  blocksPerRun: 100

storage:
  main:
    clickhouse:
      port: 9440
      database: "base"
  staging:
    clickhouse:
      port: 9440
      database: "staging"
  orchestrator:
    memory:
      maxItems: 10000