rpc:
  blocks:
    blocksPerRequest: 1000
    batchDelay: 1000
  logs:
    blocksPerRequest: 400
    batchDelay: 1000
  traces:
    enabled: false
    blocksPerRequest: 200
    batchDelay: 1000

log:
  level: debug
  pretty: true

poller:
  enabled: true
  interval: 3000
  blocksPerPoll: 1000
  fromBlock: 10000000

committer:
  enabled: true
  interval: 2000
  blocksPerCommit: 1000

failureRecoverer:
  enabled: true
  interval: 10000
  blocksPerRun: 100

storage:
  main:
    clickhouse:
      port: 9440
      database: "base"
  staging:
    clickhouse:
      port: 9440
      database: "staging"
  orchestrator:
    memory:
      maxItems: 10000