rpc:
  blocks:
    blocksPerRequest: 500
  logs:
    blocksPerRequest: 200
  traces:
    enabled: true
    blocksPerRequest: 200

log:
  level: debug
  pretty: false

poller:
  enabled: true
  interval: 1000
  blocksPerPoll: 10000

committer:
  enabled: true
  interval: 1000
  blocksPerCommit: 100

failureRecoverer:
  enabled: true
  interval: 3000
  blocksPerRun: 100

storage:
  main:
    clickhouse:
      port: 9440
      database: "base"
  staging:
    clickhouse:
      port: 9440
      database: "staging"
  orchestrator:
    memory:
      maxItems: 10000