rpc:
  url: https://1.rpc.thirdweb.com

storage:
  main:
    clickhouse:
      host: localhost
      username: admin
      password: admin
  staging:
    clickhouse:
      host: localhost
      username: admin
      password: admin